#define SUDOKU_GAME_SIZE 9
#define SUBGRID_SIZE 3

#define ROW_EXACT_MATCHING 0
#define COL_EXACT_MATCHING 81
#define COLOR_EXACT_COVER 162
#define SUBGRID_EXACT_COVER 243
#define MAX_COLS 324
#define MAX_ROWS 729